/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import mas.Mecz;
import mas.Sedzia;

/**
 *
 * @author Michał
 */
public class SedziaMecze extends javax.swing.JPanel {

    /**
     * Creates new form SedziaMecze
     */
    public SedziaMecze() {
        initComponents();
        comboBox1Values();
        comboBox2Values();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sedziaComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        meczeComboBox = new javax.swing.JComboBox();
        przypiszButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        meczeList = new javax.swing.JList();

        jLabel1.setText("Wybierz sędziego:");

        jLabel2.setText("Mecze:");

        sedziaComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sedziaComboBoxItemStateChanged(evt);
            }
        });

        jLabel3.setText("Nieprzypisane mecze:");

        przypiszButton.setText("Przypisz mecz");
        przypiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przypiszButtonActionPerformed(evt);
            }
        });

        meczeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(meczeList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(meczeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(przypiszButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sedziaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sedziaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meczeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(przypiszButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 221, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void przypiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przypiszButtonActionPerformed
        Sedzia sedzia=(Sedzia)sedziaComboBox.getSelectedItem();
        sedzia.addMecz((Mecz)meczeComboBox.getSelectedItem());
        comboBox2Values();
        listValuse((Sedzia)sedziaComboBox.getSelectedItem());
    }//GEN-LAST:event_przypiszButtonActionPerformed

    private void sedziaComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sedziaComboBoxItemStateChanged
        listValuse((Sedzia)sedziaComboBox.getSelectedItem());
    }//GEN-LAST:event_sedziaComboBoxItemStateChanged

    public void comboBox1Values() {
        sedziaComboBox.removeAllItems();
        ArrayList<Sedzia> sedziowie = (ArrayList<Sedzia>) Sedzia.getEkstensje().get(Sedzia.class);
        for (Sedzia sedzia : sedziowie) {
            sedziaComboBox.addItem(sedzia);
        }
    }
    public void comboBox2Values(){
        meczeComboBox.removeAllItems();
        ArrayList<Mecz> mecze=(ArrayList<Mecz>)Mecz.getEkstensje().get(Mecz.class);
        for(Mecz mecz:mecze){
            if(mecz.getSedzia()==null){meczeComboBox.addItem(mecz);}
        }
    }
            
    public void listValuse(Sedzia sedzia){
        DefaultListModel<Mecz> model = new DefaultListModel<Mecz>();
        for(Mecz mecze:sedzia.getMecze()){
            model.addElement(mecze);
        }    
        meczeList.setModel(model);
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox meczeComboBox;
    private javax.swing.JList meczeList;
    private javax.swing.JButton przypiszButton;
    private javax.swing.JComboBox sedziaComboBox;
    // End of variables declaration//GEN-END:variables
}
